config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
  	resources :collaborators
  end
  resources :charges, only: [:new, :create]
  devise_for :users
  resources :users, only: [:update]

  get 'about' => 'welcome#about'
  get 'upgrade' => 'charges#new'
  get 'downgrade' => 'users#downgrade'
  get 'collaborator' => 'collaborators#index'

  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
	belongs_to :wiki
	belongs_to :user	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
has_many :wikis
has_many :collaborators

after_initialize :set_role

 def standard?
	role == 'standard'
 end

 def admin?
  role == 'admin'
 end

 def premium?
 	role == 'premium'
 end

 def set_role
   role == 'standard'
 end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :collaborated_users, through: :collaborators, source: :user

  scope :visible_to, -> (user) { user && ((user.role == 'premium') || (user.role == 'admin')) ? all : where("private IS NULL or private = ?", false) }

  scope :public_only, -> { where private: [nil, false]}
  scope :private_only, -> { where private: true }

  def public?
  	!private?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 

 	rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end

   def after_sign_in_path_for(resource)
     wikis_path
   end

   
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
# The ChargesController class creates charge to users when upgrading via Stripe API  

before_action :authenticate_user!

# Create a Stripe customer object to associate with charge
#   @param: email, the string representation of the person's email
#   @param: card, an integer representation of a credit card number 
def create
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
   )
  # Changes the user role to premium
  charge = Stripe::Charge.create(
    customer: customer.id, 
    amount: amount_for_upgrade,
    description: "Premium Membership! - #{current_user.email}",
    currency: 'usd'
   )

  # @param: customer, the string representation of the customer id
  # @param: amount, an integer represenation of amount 
  # @param: description, the string representation of description 
  # @param: currency, the string representation of currancy

  current_user.update_attribute(:role, 'premium')
  flash[:notice] = "Thanks for upgrading your account!, #{current_user.email}! "
  redirect_to wikis_path(current_user) 

# Rescue block catches and displays error 
  rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
end

# Initalize payment and pass to Stripe
#   @param: key, the stirng respresentation of key
#   @param: description, the string representation of description 
#   @param: amount, an integer represenation of amount 
 
  def new  
    @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Premium Membership - #{current_user.name}",
    amount: amount_for_upgrade
   }
  end

  private
  
  # Upgrade amount
  def amount_for_upgrade
    15_00
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def index
    @users = User.all
    @wiki = Wiki.find(params[:wiki_id])
    collaborators_ids = @wiki.collaborators(:select => :user_id).collect(&:user_id)
    @wiki_users = User.where(id: collaborators_ids)
    @non_wiki_users = User.where.not(id: collaborators_ids)
  end

  def new
  end

  def create
    @wiki = Wiki.find params[:wiki_id]
    @user = User.find params[:user_id]
    @collaborator = Collaborator.create(user_id: @user.id, wiki_id: @wiki.id)

    if @collaborator.save
      flash[:notice] = "Collaborator was added."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Error saving collaborator. Please try again."
      render :new
    end
  end

  def show
    @collaborator = Collaborator.find(params[:wiki_id])
  end

  def destroy
    @collaborator = Collaborator.find_by_user_id_and_wiki_id(params[:id],params[:wiki_id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was sucessfully deleted."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error. Please try again."
      render :show
    end
  end

private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
	end

	def update
  if current_user.update_attributes(user_params)
     flash[:notice] = "User information updated"
     redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
 	end

	def downgrade
  current_user.wikis.each do |wiki|	
			wiki.update_attribute(:private, false)
	 end
  current_user.update_attribute(:role, 'standard')
	flash[:alert] = "You now have been downgrade to a standard membership. Your private wikis will become public wikis!"		                      
  redirect_to wikis_path
  end 

  private

  def user_params
	 params.require(:user).permit(:name, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
  	@wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
     @wiki = Wiki.new(wiki_params)
     @wiki.user = current_user
     authorize @wiki 
     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
     @wiki = Wiki.find(params[:id])
     @wiki.user = current_user
     if @wiki.update_attributes(wiki_params)
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.destroy
    flash[:notice] = "Wiki was successfully deleted."
    redirect_to @wiki
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

<% if current_user.role == 'standard' %>

   <h3><%= current_user.email %>, you are a "standard" user!</h3>
   <h3> Upgrade to premium membership</h3>

   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% else %>
	<h3><%= current_user.email %>, you are a "premium" user!</h3>
	<h3> Downgrade your account? Are you sure?</h3>
	<br>
	 <%= link_to "Downgrade Here", downgrade_path, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to downgrade and all your wikis will become public?' } %>
 <% end %>
 <% end %>

app/views/collaborators/index.html.erb
<h1>Manage Collaborators of Wiki</h1>

<table class = 'table'>
  <% @wiki_users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to "Remove", wiki_collaborator_path(@wiki, user), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  <% @non_wiki_users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %></td>
    </tr>
  <% end %>
  
</table>

<%= link_to "Back to Wiki", wiki_path(@wiki), class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xpedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
   <ul class="nav nav-tabs">
      <li><%= link_to "Xpedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "Upgrade/Downgrade", upgrade_path %></li>

      <div class="pull-right user-info">
         <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), current_user %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
         <% else %>
           <%= link_to "Sign In", new_user_session_path %> or
           <%= link_to "Sign Up", new_user_registration_path %>
         <% end %>
       </div>
   </ul>

      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Xpedia</h1>
<p>Created by: Cheryl Troup</p>

app/views/welcome/index.html.erb
<br>
<div class="hero-unit">

  <h1>Xpedia</h1>
  <h3>Xpedia is a SaaS app that allows users to create their own wikis!</h3>
  <p><center>
    <div class="hero-text">
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </div>
  </center></p>
</div>

app/views/wikis/_form.html.erb
<div class="col-md-8">
  <%= form_for @wiki do |f| %>

    <% if current_user.role == 'admin' || current_user.role == 'premium' %>
      <div class="form-group">
       <%= f.label :private, class: 'checkbox' do %>
       <%= f.check_box :private %> PRIVATE WIKI
      </div>
    <% end %>
    <% end %>
                 
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
    </div>

    <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
    </div>

    <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>   
    </div>
  <% end %>
</div> 

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
    
  <%= render partial: 'form', locals: { wiki: @wiki} %>

  <h2>Collaborators</h2>
    <% @wiki.collaborated_users.each do |collaborator| %>
      <p class="media-heading">
        <%= collaborator.email %>
      </p>
      <% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if policy(Wiki.new).create? %>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <% if policy(wiki).show? %>
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to (markdown_to_html wiki.title), wiki %>
       </h4>
     </div>
   </div>
<% end %>
<% end %>

app/views/wikis/new.html.erb
 <h1>Create a New Wiki</h1>
 
    <%= render partial: 'form', locals: { wiki: @wiki} %>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

  <% if policy(@wiki).edit? %>
	<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% end %>

  <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>

  <p><%= markdown_to_html @wiki.body %></p>

  <% if current_user.role == 'premium' %>  

<%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-success' %>
 
  <table class = "table table-bordered">
  <% @wiki.collaborated_users.each do |collaborator| %>
    <tr>
      <td><%= collaborator.email %></td> 
    </tr>
                               <% end %>           
    </table>

  <% end %>